# Generated by Django 4.0.1 on 2022-01-08 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NEW SLETTER!', max_length=50)),
                ('subtitle', models.CharField(default='UP TO 70% OFF', max_length=50)),
                ('caption', models.CharField(default='FOOD', max_length=10)),
                ('signup_visibility', models.CharField(choices=[(True, 'Show Sign up'), (False, 'Hide Sign up')], default=True, max_length=50)),
                ('advertise_visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('division', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('banner_img_path', models.CharField(max_length=200)),
                ('category_img_path', models.CharField(max_length=200)),
                ('policy', models.TextField(null=True)),
                ('meta_keywords', models.CharField(max_length=400, null=True)),
                ('meta_description', models.TextField(null=True)),
                ('slug', models.SlugField()),
                ('large', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medium', models.DecimalField(decimal_places=2, max_digits=6)),
                ('small', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], default='N', max_length=50)),
                ('contact', models.CharField(max_length=15, unique=True)),
                ('social_media_link', models.CharField(max_length=200)),
                ('birthdate', models.DateTimeField(auto_now=True)),
                ('membership', models.CharField(choices=[('G', 'Gold Badge'), ('S', 'Silver Badge'), ('B', 'Bronge Badge')], default='B', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('meta_keywords', models.CharField(max_length=400, null=True)),
                ('meta_description', models.TextField(null=True)),
                ('merchant_id', models.PositiveBigIntegerField(default=1)),
                ('video_url', models.URLField(max_length=300)),
                ('slug', models.SlugField()),
                ('product_description', models.TextField()),
                ('product_material', models.TextField()),
                ('product_brand', models.CharField(max_length=100)),
                ('packing_type', models.CharField(choices=[('A', 'Bottle'), ('B', 'Plastic Box'), ('C', 'Foil Sealed Box'), ('D', 'Cart Box'), ('E', 'Poly Bag')], default='E', max_length=100)),
                ('product_sale', models.DecimalField(decimal_places=2, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('O', 'out_of_stock'), ('S', 'in_stock'), ('L', 'running_low'), ('B', 'banned')], default='S', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(default='Product Review', max_length=100)),
                ('review_body', models.TextField()),
                ('rating', models.SmallIntegerField()),
                ('verification', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img_src', models.ImageField(upload_to='')),
                ('img_title', models.CharField(max_length=100, null=True)),
                ('img_alt', models.CharField(max_length=400, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'On Progres'), (2, 'On The Way'), (3, 'Delivered'), (4, 'Cancel'), (5, 'Failed')], default=0, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_addr_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.billingaddress')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.customer')),
            ],
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.customer'),
        ),
    ]
