# Generated by Django 4.0.1 on 2022-01-16 06:53

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_billingaddress_user_billingaddress_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner_img_path',
            field=models.ImageField(blank=True, null=True, upload_to='shop_category//<django.db.models.fields.CharField>_category_type_2022-01-16 12:53:33.299802.jpg'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_img_path',
            field=models.ImageField(blank=True, null=True, upload_to='shop_category//<django.db.models.fields.CharField>_category_type_2022-01-16 12:53:33.299802.jpg'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.user_directory_path),
        ),
    ]
