# Generated by Django 3.2.11 on 2022-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_category_banner_img_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner_img_path',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_img_path',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
