# Generated by Django 3.2.11 on 2022-01-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_category_id_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sale',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
