# Generated by Django 3.2.11 on 2022-01-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20220119_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_addr_id',
            new_name='billing_addr',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='product_id',
            new_name='product',
        ),
    ]
